enum ErrorType {
    FIELD_REQUIRED = "FIELD REQUIRED",
    FIELD_NOT_UNIQUE = "FIELD NOT UNIQUE",
    GAME_NOT_FOUND = "GAME NOT FOUND",
    NUMBER_OF_STARTING_POINTS_EXCEEDED = "NUMBER OF STARTING POINTS EXCEEDED"
}

export default ErrorType;