enum ErrorType {
    FIELD_REQUIRED = "FIELD REQUIRED",
    FIELD_NOT_UNIQUE = "FIELD NOT UNIQUE",
    GAME_NOT_FOUND = "GAME NOT FOUND",
    NUMBER_OF_STARTING_POINTS_EXCEEDED = "NUMBER OF STARTING POINTS EXCEEDED",
    USER_NOT_FOUND = "USER NOT FOUND",
    CANNOT_START_GAME = "CANNOT START GAME",
    GAME_STARTED_TWICE = "GAME STARTED TWICE",
    INVALID_BOARD = "INVALID BOARD",
    GAME_NOT_STARTED_YET = "GAME_NOT_STARTED_YET",
    INCORRECT_PLAYER_ACTION = "INCORRECT_PLAYER_ACTION",
    INVALID_PATH = "INVALID_PATH"
}

export default ErrorType;